<?php

namespace cano\UEKCBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClassroomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassroomRepository extends EntityRepository
{
    public function propagate($ent, $em) {
        $target = 'Classroom';
        $targetParent = 'Building';
        $setter = 'setBuilding';
        $t = $em->getRepository('canoUEKCBundle:'.$target)->findAll();
        //!! this should resolve to proper entry of parent!
        $tParent = $em->getRepository('canoUEKCBundle:'.$targetParent)->find(1);
        $tClass = 'cano\\UEKCBundle\\Entity\\'.$target;

        $alreadyThere = false;
        $currentId = '';
        for ($j = 0; $j < count($t); $j++) {
            if ($ent == $t[$j]->getName()) {
                $alreadyThere = true;
                $currentId = $t[$j]->getId();
            }
        }
        if ($alreadyThere == false) {
            $entItem = new $tClass();
            $entItem->{$setter}($tParent);
            $entItem->setName($ent);
            $em->persist($entItem);
            $em->flush();
            $currentId = $entItem->getId();
        }
        return $em->getRepository('canoUEKCBundle:'.$target)->find($currentId);
    }

}
