<?php

namespace cano\UEKCBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CrawlStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrawlStatusRepository extends EntityRepository
{
}
