<?php

namespace cano\UEKCBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherRepository extends EntityRepository
{
    public function propagate($ent, $mewAddress, $photoAddress, $em) {
        $target = 'Teacher';
        $targetParent = 'Degrees';
        $setter = 'setDegree';
        $t = $em->getRepository('canoUEKCBundle:'.$target)->findAll();
        $targetClass = 'cano\\UEKCBundle\\Entity\\'.$target;

        $currentId = 1;
        $degrees = $em->getRepository('canoUEKCBundle:Degrees')->findAll();
        for ($j = 0; $j < count($degrees); $j++) {
            if (strpos($ent, $degrees[$j]->getName().' ') === 0) {
                $currentId = $degrees[$j]->getId();
                $ent = substr($ent, strlen($degrees[$j]->getName())+1);
            }
        }

        $degree = $em->getRepository('canoUEKCBundle:Degrees')->find($currentId);
        $tParent = $em->getRepository('canoUEKCBundle:'.$targetParent)->find($degree);

        $teacherName = substr($ent, 0, strpos($ent, ' '));
        $teacherLastname = substr($ent, strpos($ent, ' ') + 1);

        $alreadyThere = false;
        $currentId = '';
        for ($j = 0; $j < count($t); $j++) {
            if ($teacherName == $t[$j]->getName() && $teacherLastname == $t[$j]->getLastname()) {
                $alreadyThere = true;
                $currentId = $t[$j]->getId();
            }
        }
        if ($alreadyThere == false) {
            $entItem = new $targetClass();
            $entItem->{$setter}($tParent);
            $entItem->setName($teacherName);
            $entItem->setLastname($teacherLastname);
            $entItem->setMewAddress($mewAddress);
            $entItem->setPhotoAddress($photoAddress);
            $entItem->setRating(0);
            $em->persist($entItem);
            $em->flush();
            $currentId = $entItem->getId();
        }
        return $em->getRepository('canoUEKCBundle:'.$target)->find($currentId);
    }

}
